### ISSUE TITLE
bug in cleaning data

### ISSUE THREAD

**Issue by lucasrodes** [lucasrodes/whatsapp-stats#2]
For some chat formats, the script fails to clean the data.

```
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    data = cf.clean_data(lines)
  File "whatsapp-stats/chatformat.py", line 65, in clean_data
    data[-1][2] = data[-1][2] + "\n" + line
IndexError: list index out of range
```

**Comment by lucasrodes** [comment]
Modified the regular expressions. This should be fixed by now.
